#!/usr/bin/env python3
"""NIST SP-800-22 Randomness Tests.

This script implements key statistical tests from the NIST SP-800-22 suite
in pure Python using only standard library modules. It evaluates the randomness
of a bitstream generated by the African Fractal Hash (uxandeh).

Tests Implemented:
1. Frequency (Monobit) Test
2. Frequency Test within a Block (Block size: 128 bits)
3. Runs Test
4. Cumulative Sums (Cusum) Test (Forward and Backward)

All code and comments follow British English spelling conventions.
"""

import sys
import os
import math

# Add python directory to path to load local uxandeh package
sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), "python"))
from uxandeh import uxandeh


def igamc(a: float, x: float) -> float:
    """Compute the regularised upper incomplete gamma function igamc(a, x).

    Uses series expansion for lower incomplete gamma when x < a + 1.0,
    and a continued fraction via Lentz's method for upper incomplete gamma when x >= a + 1.0.
    """
    if x <= 0.0 or a <= 0.0:
        return 1.0 if x == 0.0 else 0.0

    if x < a + 1.0:
        # Series expansion for lower incomplete gamma
        sum_val = 1.0 / a
        temp = sum_val
        n = 1
        while n < 1000:
            temp = temp * x / (a + n)
            sum_val += temp
            if abs(temp) < abs(sum_val) * 1e-15:
                break
            n += 1
        gammp = sum_val * math.exp(-x + a * math.log(x) - math.lgamma(a))
        return 1.0 - gammp
    else:
        # Continued fraction for upper incomplete gamma using Lentz's method
        tiny = 1e-30
        b = x + 1.0 - a
        c = 1.0 / tiny
        d = 1.0 / b
        h = d
        for i in range(1, 1000):
            an = -i * (i - a)
            b += 2.0
            d = b + an * d
            if abs(d) < tiny:
                d = tiny
            c = b + an / c
            if abs(c) < tiny:
                c = tiny
            d = 1.0 / d
            del_val = c * d
            h *= del_val
            if abs(del_val - 1.0) < 1e-15:
                break
        gammq = h * math.exp(-x + a * math.log(x) - math.lgamma(a))
        return gammq


def phi(x: float) -> float:
    """Standard normal cumulative distribution function (CDF)."""
    return 0.5 * math.erfc(-x / math.sqrt(2.0))


def frequency_monobit_test(bits: list) -> float:
    """1. Frequency (Monobit) Test.

    Evaluates whether the proportion of ones and zeros is approximately equal.
    """
    n = len(bits)
    s_n = sum(2 * b - 1 for b in bits)
    s_obs = abs(s_n) / math.sqrt(n)
    p_value = math.erfc(s_obs / math.sqrt(2.0))
    return p_value


def frequency_block_test(bits: list, M: int = 128) -> float:
    """2. Frequency Test within a Block.

    Determines whether the frequency of ones in an M-bit block is approx M/2.
    """
    n = len(bits)
    N = n // M
    if N == 0:
        return 0.0

    chi_sq = 0.0
    for i in range(N):
        block = bits[i * M : (i + 1) * M]
        pi_i = sum(block) / M
        chi_sq += (pi_i - 0.5) ** 2

    chi_sq_obs = 4.0 * M * chi_sq
    p_value = igamc(N / 2.0, chi_sq_obs / 2.0)
    return p_value


def runs_test(bits: list) -> float:
    """3. Runs Test.

    Measures total number of runs (consecutive identical bits) in the sequence.
    """
    n = len(bits)
    pi = sum(bits) / n
    
    # Check if Monobit frequency test fails pre-requisite
    if abs(pi - 0.5) >= (2.0 / math.sqrt(n)):
        return 0.0

    # Calculate number of runs
    v_n = 1
    for i in range(n - 1):
        if bits[i] != bits[i + 1]:
            v_n += 1

    numerator = abs(v_n - 2.0 * n * pi * (1.0 - pi))
    denominator = 2.0 * math.sqrt(2.0 * n) * pi * (1.0 - pi)
    p_value = math.erfc(numerator / denominator)
    return p_value


def cumulative_sums_test(bits: list, mode: str = "forward") -> float:
    """4. Cumulative Sums (Cusum) Test.

    Checks if cumulative sum excursions of the centered bit sequences are too large.
    """
    n = len(bits)
    x = [2 * b - 1 for b in bits]
    
    s = [0] * (n + 1)
    if mode == "forward":
        for i in range(n):
            s[i + 1] = s[i] + x[i]
    else:  # backward
        for i in range(n):
            s[i + 1] = s[i] + x[n - 1 - i]

    z = max(abs(val) for val in s)
    if z == 0:
        return 1.0

    # Compute sum 1
    sum1 = 0.0
    k_min = int(math.floor((-n / z + 1.0) / 4.0))
    k_max = int(math.floor((n / z - 1.0) / 4.0))
    for k in range(k_min, k_max + 1):
        term1 = phi((4 * k + 1) * z / math.sqrt(n))
        term2 = phi((4 * k - 1) * z / math.sqrt(n))
        sum1 += (term1 - term2)

    # Compute sum 2
    sum2 = 0.0
    k_min2 = int(math.floor((-n / z - 3.0) / 4.0))
    k_max2 = int(math.floor((n / z - 1.0) / 4.0))
    for k in range(k_min2, k_max2 + 1):
        term1 = phi((4 * k + 3) * z / math.sqrt(n))
        term2 = phi((4 * k + 1) * z / math.sqrt(n))
        sum2 += (term1 - term2)

    p_value = 1.0 - sum1 + sum2
    return p_value


def generate_bitstream(num_blocks: int = 10000) -> list:
    """Generate a large bitstream by hashing sequential inputs using uxandeh.

    Inputs are sequential integer strings "0", "1", "2", ...
    This tests the diffusion/avalanche quality of the hash outputs.
    """
    print(f"[-] Generating bitstream from {num_blocks} sequential hash iterations...")
    bitstream = []
    for i in range(num_blocks):
        digest = uxandeh(str(i).encode("utf-8"))
        for byte in digest:
            for shift in range(7, -1, -1):
                bitstream.append((byte >> shift) & 1)
    print(f"    [Generated] {len(bitstream)} bits.")
    return bitstream


def run_all_randomness_tests():
    # 10,000 blocks * 256 bits/block = 2,560,000 bits
    bits = generate_bitstream(10000)
    
    print("\n====================================================")
    print("NIST SP-800-22 Randomness Test Suite Results")
    print("====================================================")
    
    tests = [
        ("Frequency (Monobit) Test", lambda b: frequency_monobit_test(b)),
        ("Frequency Test within a Block (M=128)", lambda b: frequency_block_test(b, 128)),
        ("Runs Test", lambda b: runs_test(b)),
        ("Cumulative Sums (Forward) Test", lambda b: cumulative_sums_test(b, "forward")),
        ("Cumulative Sums (Backward) Test", lambda b: cumulative_sums_test(b, "backward")),
    ]
    
    failed = False
    for name, run_test in tests:
        p_val = run_test(bits)
        status = "PASSED" if p_val >= 0.01 else "FAILED"
        print(f"{name:40s} | p-value: {p_val:.6f} | Status: {status}")
        if p_val < 0.01:
            failed = True
            
    print("====================================================")
    if failed:
        print("[Result] Randomness check: FAILED! One or more tests did not meet p-value >= 0.01.")
        sys.exit(1)
    else:
        print("[Result] Randomness check: PASSED! All tests met p-value >= 0.01.")
        sys.exit(0)


if __name__ == "__main__":
    run_all_randomness_tests()
